#!/bin/sh

exit 0

## NOT RUNNING
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-h|--hdmi)
	pacmd set-card-profile alsa_card.pci-0000_00_1f.3 output:hdmi-stereo && echo "HDMI profile is active" && kdialog --passivepopup "Audio output changed to HDMI" --title="Audio profile changed" 2
    
    #pacmd set-default-sink 0
    #pacmd set-card-profile alsa_card.usb-046d_HD_Pro_Webcam_C920_45ADDDAF-02 off # Turn off Webcam Microphone entry
	#pacmd set-card-profile alsa_card.pci-0000_00_1f.3 output:hdmi-stereo+input:analog-stereo && echo "HDMI profile is active" && kdialog --passivepopup "Audio output changed to HDMI" --title="Audio profile changed" 2
	shift
	;;
	-a|--analog)
    pacmd set-card-profile alsa_card.usb-KTMicro_KT_USB_Audio_2021-06-25-0000-0000-0000--00 output:analog-stereo+input:mono-fallback && echo "Analog Profile is active" && kdialog --passivepopup "Audio output changed to ANALOG" --title="Audio profile changed" 2

    #pacmd set-card-profile alsa_card.usb-046d_HD_Pro_Webcam_C920_45ADDDAF-02 off # Turn off Webcam Microphone entry
    # pacmd set-default-sink 1
    #pacmd set-card-profile alsa_card.usb-046d_HD_Pro_Webcam_C920_45ADDDAF-02 off # Turn off Webcam Microphone entry
	#pacmd set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo && echo "Analog Profile is active" && kdialog --passivepopup "Audio output changed to ANALOG" --title="Audio profile changed" 2

	shift
	;;
	*)
	echo "Choose -h (--hdmi) or -a (--analog)"
	exit 3
	;;
esac
done
if [[ $# -ne $1 ]]; then
	echo "Choose -h (--hdmi) or -a (--analog)"
fi

